### ISSUE TITLE
AvaliacaoA2 - List entries in the API

### ISSUE THREAD

**Issue by Vinschers** [Miller-GS/MC426A-TV-Application#5]
## Description
Our API should connect to the TVDB API and list searched entries with respective filters.

## Tasks

- [x] Unit tests

### Create Endpoint
- [x] Create endpoint with filters as parameters:
- Whether the user wants to search for movies, series or both;
- Name
- Genre
- Year

### Connect private key to TMDB
- [x] Create account at TMDB
- [x] Use key as environment variable

**Comment by Vinschers** [comment]
Closed with #9.
